/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddressAndHukou: typeof import('./components/hr/AddressAndHukou.vue')['default']
    BankInfo: typeof import('./components/hr/BankInfo.vue')['default']
    BasicInfo: typeof import('./components/hr/BasicInfo.vue')['default']
    CertificateList: typeof import('./components/hr/CertificateList.vue')['default']
    CompanyPicker: typeof import('./components/hr/CompanyPicker.vue')['default']
    FamilyList: typeof import('./components/hr/FamilyList.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    IdCardInfo: typeof import('./components/hr/IdCardInfo.vue')['default']
    PrivacyDialog: typeof import('./components/hr/PrivacyDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudyExperienceList: typeof import('./components/hr/StudyExperienceList.vue')['default']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    UploadSection: typeof import('./components/hr/UploadSection.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCascader: typeof import('vant/es')['Cascader']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCol: typeof import('vant/es')['Col']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanDialog: typeof import('vant/es')['Dialog']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanLoading: typeof import('vant/es')['Loading']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanRow: typeof import('vant/es')['Row']
    VanSearch: typeof import('vant/es')['Search']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTag: typeof import('vant/es')['Tag']
    VanToast: typeof import('vant/es')['Toast']
    VanUploader: typeof import('vant/es')['Uploader']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
    WorkExperienceList: typeof import('./components/hr/WorkExperienceList.vue')['default']
  }
}
